# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Rcpp Stochastic Simulation Algorithm
#' @export
rssa <- function(rate, max_time, seed = 0L) {
    .Call(`_wassa_rssa`, rate, max_time, seed)
}

